from pathlib import Path

import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist

from nucleitracking.pipeline.config import PipelineConfig


def merge_centroids(current_centroids, centroids_to_add, max_distance=25):
    """
    Merges centroids from `centroids_to_add` into `current_centroids` if they are within `max_distance`.
    """
    axes = ["px_z", "px_y", "px_x"]

    merged_centroids = current_centroids.copy()
    add_to_drop = set()
    merged_to_drop = set()

    for timepoint in set(current_centroids["timepoint"]).intersection(
        set(centroids_to_add["timepoint"])
    ):
        current = current_centroids[current_centroids["timepoint"] == timepoint]
        to_add = centroids_to_add[centroids_to_add["timepoint"] == timepoint]

        x_current = current[axes].values
        x_add = to_add[axes].values

        distances = cdist(x_current, x_add)
        close_pairs = np.argwhere(distances < max_distance)

        for i, j in close_pairs:
            # keep the centroids farthest from the edge
            if (
                to_add.iloc[j]["uv_distance_from_edge"]
                < current.iloc[i]["uv_distance_from_edge"]
            ):
                add_to_drop.add(to_add.index[j])
            else:
                merged_to_drop.add(current.index[i])

    out = pd.concat(
        [merged_centroids.drop(merged_to_drop), centroids_to_add.drop(add_to_drop)],
        ignore_index=True,
    )

    return out


def run_merge_centroids(dataset: Path, config: PipelineConfig):
    """
    Reads the 2D centroids generated by the batched script on the cluster,
    and merges them into a single 3D global cloud.
    """
    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "new_centroids.csv"
    if out_file.exists():
        print(
            f"[{dataset.name}] Merging 3D Centroids (Skipped: {out_file.name} exists)"
        )
        return

    print(f"[{dataset.name}] Merging 3D Centroids...")
    csv_path = out_dir / "centroids_2d_from_stack.csv"

    if not csv_path.exists():
        print(f"  [Error] {csv_path} not found.")
        print("  ACTION REQUIRED:")
        print(
            "  Run the batched 2D clustering script and place the output here before resuming local_post."
        )
        return

    centroids = pd.read_csv(csv_path)

    centroids["px_area"] = centroids["px_area"].abs()
    centroids = centroids[centroids["px_area"] < 300]

    new_centroids = None
    meshes = centroids["mesh_name"].unique()

    for mesh_name in meshes:
        print(f"  Merging {mesh_name} into global cloud")
        to_add = centroids[centroids["mesh_name"] == mesh_name]

        if new_centroids is None:
            new_centroids = to_add
            continue

        new_centroids = merge_centroids(
            new_centroids,
            to_add,
            max_distance=config.local_post.reconstruct_3d.max_distance,
        )

    new_centroids = new_centroids.dropna()
    new_centroids = new_centroids.reset_index(drop=True)
    new_centroids["id_prev"] = new_centroids.index.astype(np.uint32)

    # Convert column names to match downstream tracking expectations
    new_centroids = new_centroids.rename(
        columns={
            "timepoint": "FRAME",
            "px_x": "POSITION_X",
            "px_y": "POSITION_Y",
            "px_z": "POSITION_Z",
        }
    )

    out_file = out_dir / "new_centroids.csv"
    new_centroids.to_csv(out_file, index=False)
    print(f"  Saved reconstructed 3D centroids to {out_file}")


def run_napari_visualization(dataset: Path, config: PipelineConfig):
    """
    Opens the final lineages CSV in a 3D Napari viewer, mirroring coordinates
    and applying a discrete color palette to track IDs.
    """
    out_dir = dataset / f"tracking_{config.param_set_name}"
    final_csv = out_dir / "final_lineages.csv"

    if not final_csv.exists():
        print(f"  [Warning] {final_csv.name} not found. Skipping visualization.")
        return

    print(f"[{dataset.name}] Opening Napari Visualization...")
    import colorcet as cc
    import napari

    df = pd.read_csv(final_csv)

    # Reflect coordinates to "unwrap" the cylinder if possible
    if "POSITION_Z" in df.columns and "POSITION_X" in df.columns.values:
        df["reflection_z"] = 2.1 * df["POSITION_Z"].max() - df["POSITION_Z"]
        df["reflection_x"] = df["POSITION_X"].max() - df["POSITION_X"]
        df["is_reflected"] = df["POSITION_X"] > df["POSITION_X"].max() / 2

        df["display_x"] = df["reflection_x"] * df["is_reflected"] + df["POSITION_X"] * (
            ~df["is_reflected"]
        )
        df["display_z"] = df["reflection_z"] * df["is_reflected"] + df["POSITION_Z"] * (
            ~df["is_reflected"]
        )
    else:
        df["display_x"] = df.get("POSITION_X", np.zeros(len(df)))
        df["display_z"] = df.get("POSITION_Z", np.zeros(len(df)))

    column = "track_id"
    if column not in df.columns:
        print(
            f"  [Warning] '{column}' not in {final_csv.name}. Displaying points in white."
        )
        color = "white"
        properties = None
    else:
        track_ids = np.nan_to_num(df[column].unique())
        palette = cc.glasbey  # Discrete categorical palette
        color_map = {
            track: palette[i % len(palette)] for i, track in enumerate(track_ids)
        }
        color = [color_map[track] for track in df[column].fillna(0)]
        properties = {"spot id": df.index, column: df[column]}

    # Prepare coordinate matrix (T, Z, Y, X in napari by default, but we'll use T, X, Y, Z for 3D)
    # Napari expects (T, Z, Y, X) for points to be displayed in the correct orientation usually.
    coords = df[["FRAME", "display_x", "POSITION_Y", "display_z"]].values

    viewer = napari.Viewer(ndisplay=3)
    viewer.add_points(
        coords,
        name="Tracked Lineages",
        properties=properties,
        face_color=color,
        size=13,
    )
    viewer.theme = "dark"
    napari.run()
