import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import matplotlib as mpl
import napari
import numpy as np
import pandas as pd
from dtaidistance import dtw_ndim
from natsort import natsorted
from scipy.optimize import linear_sum_assignment
from scipy.spatial.distance import cdist
from sklearn.decomposition import PCA
from tqdm import tqdm

from nucleitracking.models.division_tracking import map_divisions
from nucleitracking.models.lap_tracking import run_lap_tracking
from nucleitracking.pipeline.config import PipelineConfig


def merge_centroids(current_centroids, centroids_to_add, max_distance: float = 25):
    """
    Merges centroids from `centroids_to_add` into `current_centroids` if they are within `max_distance`.
    """
    axes = ["px_z", "px_y", "px_x"]

    merged_centroids = current_centroids.copy()
    add_to_drop = set()
    merged_to_drop = set()

    for timepoint in set(current_centroids["timepoint"]).intersection(
        set(centroids_to_add["timepoint"])
    ):
        current = current_centroids[current_centroids["timepoint"] == timepoint]
        to_add = centroids_to_add[centroids_to_add["timepoint"] == timepoint]

        x_current = current[axes].values
        x_add = to_add[axes].values

        distances = cdist(x_current, x_add)
        close_pairs = np.argwhere(distances < max_distance)

        for i, j in close_pairs:
            # keep the centroids farthest from the edge
            if (
                to_add.iloc[j]["uv_distance_from_edge"]
                < current.iloc[i]["uv_distance_from_edge"]
            ):
                add_to_drop.add(to_add.index[j])
            else:
                merged_to_drop.add(current.index[i])

    out = pd.concat(
        [merged_centroids.drop(merged_to_drop), centroids_to_add.drop(add_to_drop)],
        ignore_index=True,
    )

    return out


def run_merge_centroids(dataset: Path, config: PipelineConfig):
    """
    Reads the 2D centroids generated by the batched script on the cluster,
    and merges them into a single 3D global cloud.
    """
    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "new_centroids.csv"
    if out_file.exists():
        print(
            f"[{dataset.name}] Merging 3D Centroids (Skipped: {out_file.name} exists)"
        )
        return

    print(f"[{dataset.name}] Merging 3D Centroids...")
    csv_path = out_dir / "centroids_2d_from_stack.csv"

    if not csv_path.exists():
        print(f"  [Error] {csv_path} not found.")
        print("  ACTION REQUIRED:")
        print(
            "  Run the batched 2D clustering script and place the output here before resuming local_post."
        )
        return

    centroids = pd.read_csv(csv_path)

    centroids["px_area"] = centroids["px_area"].abs()
    centroids = centroids[centroids["px_area"] < 300]

    new_centroids = None
    meshes = centroids["mesh_name"].unique()

    for mesh_name in meshes:
        print(f"  Merging {mesh_name} into global cloud")
        to_add = centroids[centroids["mesh_name"] == mesh_name]

        if new_centroids is None:
            new_centroids = to_add
            continue

        new_centroids = merge_centroids(
            new_centroids,
            to_add,
            max_distance=config.local_post.reconstruct_3d.max_distance,
        )

    new_centroids = new_centroids.dropna()
    new_centroids = new_centroids.reset_index(drop=True)
    new_centroids["id_prev"] = new_centroids.index.astype(np.uint32)

    # Convert column names to match downstream tracking expectations
    new_centroids = new_centroids.rename(
        columns={
            "timepoint": "frame",
        }
    )

    # visualize the new centroids in napari to sanity check and determine NC timing
    viewer = napari.Viewer()
    color_map = dict(zip(meshes, list(mpl.colormaps["tab10"].colors)))
    colors = [color_map[mesh] for mesh in new_centroids["mesh_name"]]
    viewer.add_points(
        new_centroids[["frame", "px_z", "px_y", "px_x"]].values,
        name=f"Merged Centroids {config.param_set_name}",
        properties={"mesh_name": new_centroids["mesh_name"]},
        face_color=colors,
        size=new_centroids["px_area"] ** 0.5,
        shading="spherical",
    )

    napari.run()

    out_file = out_dir / "new_centroids.csv"
    new_centroids.to_csv(out_file, index=True, index_label="ix")
    print(f"  Saved reconstructed 3D centroids to {out_file}")


def run_merge_3d_tracking(dataset: Path, config: PipelineConfig):
    """
    Optionally merges 3D bounding-box segmentation centroids (from bbox_segment.sh)
    into the reconstructed cloud produced by run_merge_centroids.

    3D centroids are filtered to a frame window and edge-rejected before merging.
    Pole-cell centroids live far from the UV surface, so they should not overlap
    spatially with any existing 2D centroid; the spatial guard is a safety net only.
    """
    params = config.local_post.merge_3d_tracking
    if not params.enabled:
        return

    out_dir = dataset / f"tracking_{config.param_set_name}"
    merged_file = out_dir / "new_centroids.csv"
    backup_file = out_dir / "new_centroids_pre_3d.csv"

    if backup_file.exists():
        print(f"[{dataset.name}] Merge 3D Tracking (Skipped: already applied)")
        return

    if not merged_file.exists():
        print(f"  [Warning] {merged_file.name} not found — run merge_centroids first.")
        return

    csv_path = (
        Path(params.csv_path) if params.csv_path else out_dir / "centroids_3d.csv"
    )
    if not csv_path.exists():
        print(f"  [Error] 3D centroids file not found at {csv_path}")
        return

    print(f"[{dataset.name}] Merging 3D tracking centroids from {csv_path.name}...")

    new_centroids = pd.read_csv(merged_file, index_col="ix")
    centroids_3d = pd.read_csv(csv_path)

    # ── Frame window filter ───────────────────────────────────────────────────
    if params.start_frame is not None:
        centroids_3d = centroids_3d[centroids_3d["timepoint"] >= params.start_frame]
    if params.end_frame is not None:
        centroids_3d = centroids_3d[centroids_3d["timepoint"] <= params.end_frame]

    # ── Edge rejection ────────────────────────────────────────────────────────
    if params.crop_shape is not None and params.edge_cutoff > 0:
        z_max, _y_max, x_max = params.crop_shape
        c = params.edge_cutoff
        z_ok = (centroids_3d["crop_z"] >= c) & (centroids_3d["crop_z"] <= z_max - c)
        # skip rejection near the upper y edge (open face of bounding box)
        y_ok = centroids_3d["crop_y"] >= c
        x_ok = (centroids_3d["crop_x"] >= c) & (centroids_3d["crop_x"] <= x_max - c)
        centroids_3d = centroids_3d[z_ok & y_ok & x_ok]

    if centroids_3d.empty:
        print("  No 3D centroids remain after filtering — nothing merged.")
        return

    print(f"  {len(centroids_3d)} 3D centroids after filtering")

    # get radius of 3d sphere with equal volume
    centroids_3d["radius"] = (centroids_3d["area"] * (3 / (4 * np.pi))) ** (1 / 3)

    # ── Map to shared column schema ───────────────────────────────────────────
    centroids_3d_mapped = pd.DataFrame(
        {
            "frame": centroids_3d["timepoint"].values,
            "px_z": centroids_3d["global_z"].values,
            "px_y": centroids_3d["global_y"].values,
            "px_x": centroids_3d["global_x"].values,
            "intensity_mean": centroids_3d["intensity_mean"].values,
            "intensity_std": centroids_3d["intensity_std"].values,
            "mesh_name": centroids_3d["bbox_name"].values,
            # UV columns: 0 so any nearby UV centroid wins; NaN where not applicable
            "uv_distance_from_edge": 0.0,
            "uv_v": np.nan,
            "uv_u": np.nan,
            "uv_z": np.nan,
            "uv_area": np.nan,
            "area_distortion": np.nan,
            "px_area": np.pi
            * centroids_3d["radius"] ** 2,  # surface area of sphere with equal volume
        }
    )

    # ── Spatial deduplication: drop 3D centroids too close to existing ones ──
    axes = ["px_z", "px_y", "px_x"]
    to_drop = set()

    for frame, group_3d in centroids_3d_mapped.groupby("frame"):
        group_2d = new_centroids[new_centroids["frame"] == frame]
        if group_2d.empty:
            continue
        distances = cdist(group_2d[axes].values, group_3d[axes].values)
        close_cols = np.where((distances < params.max_merge_distance).any(axis=0))[0]
        for col_idx in close_cols:
            to_drop.add(group_3d.index[col_idx])

    centroids_3d_mapped = centroids_3d_mapped.drop(index=to_drop)

    # ── Concatenate and re-index ──────────────────────────────────────────────
    result = pd.concat([new_centroids, centroids_3d_mapped], ignore_index=True)
    result = result.reset_index(drop=True)
    result["id_prev"] = result.index.astype(np.uint32)

    new_centroids.to_csv(backup_file, index=True, index_label="ix")
    result.to_csv(merged_file, index=True, index_label="ix")
    print(
        f"  {len(new_centroids)} -> {len(result)} centroids "
        f"(+{len(result) - len(new_centroids)} from 3D, "
        f"{len(to_drop)} discarded as duplicates)"
    )


def run_tracking(dataset: Path, config: PipelineConfig):
    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "lap_tracked_spots.csv"
    if out_file.exists():
        print(f"[{dataset.name}] LAP Tracking (Skipped: {out_file.name} exists)")
        return

    print(f"[{dataset.name}] Running LAP Tracking...")

    # Load 3D centroids generated from the local post-processing Reconstruction step
    # For now, we assume a standard name
    centroids_path = dataset / f"tracking_{config.param_set_name}" / "new_centroids.csv"
    if not centroids_path.exists():
        print(
            f"  [Warning] Centroids file not found at {centroids_path}. Skipping tracking."
        )
        return

    centroids = pd.read_csv(centroids_path, index_col="ix")

    # Filter frames based on user configuration
    if config.local_post.tracking.start_frame > 0:
        print(
            f"  Filtering out frames before {config.local_post.tracking.start_frame}..."
        )
        centroids = centroids[
            centroids["frame"] >= config.local_post.tracking.start_frame
        ]

    if config.local_post.tracking.skip_frames:
        print(f"  Skipping frames: {config.local_post.tracking.skip_frames}...")
        centroids = centroids[
            ~centroids["frame"].isin(config.local_post.tracking.skip_frames)
        ]

    # Run the new Python LAP tracker instead of TrackMate
    spots_df, _graph = run_lap_tracking(
        centroids,
        max_distance=config.local_post.tracking.search_radius,
        max_gap_frames=config.local_post.tracking.max_gap_frames,
    )

    # Save preliminary tracking results
    out_dir = dataset / f"tracking_{config.param_set_name}"
    spots_df.to_csv(out_dir / "lap_tracked_spots.csv", index=True, index_label="ix")
    print(f"  Saved LAP tracked spots to {out_dir / 'lap_tracked_spots.csv'}")


def interpolate_spots(spots_df: pd.DataFrame):
    """
    Interpolates the positions of spots in the spots_df to fill in gaps between frames.
    This does not use the graph structure
    """

    spots_df["frame_gap"] = spots_df["frame"] - spots_df["parent_id"].map(
        spots_df["frame"]
    )
    spots_df["is_interpolated"] = False

    children = spots_df[spots_df["frame_gap"] > 1]

    new_rows = []
    new_indices = []
    next_highest_id = spots_df.index.max() + 1

    for idx, child in children.iterrows():
        parent = spots_df.loc[child["parent_id"]]
        gap = child["frame_gap"]

        next_parent_id = child["parent_id"]

        for i in range(1, int(gap)):
            interp_spot = {
                "frame": parent["frame"] + i,
                "px_z": parent["px_z"] + (child["px_z"] - parent["px_z"]) * i / gap,
                "px_y": parent["px_y"] + (child["px_y"] - parent["px_y"]) * i / gap,
                "px_x": parent["px_x"] + (child["px_x"] - parent["px_x"]) * i / gap,
                "track_id": parent["track_id"],
                "parent_id": next_parent_id,
                "is_interpolated": True,
            }

            row = spots_df.loc[idx].copy()
            row.update(interp_spot)
            new_rows.append(row)
            new_indices.append(next_highest_id)
            next_parent_id = next_highest_id
            next_highest_id += 1

        spots_df.loc[idx, "parent_id"] = next_parent_id

    if new_rows:
        new_spots_df = pd.DataFrame(new_rows, index=new_indices)
        spots_df = pd.concat([spots_df, new_spots_df])

    return spots_df.sort_values("frame")


def reassign_skipped_frames(spots_df: pd.DataFrame, skip_frames: list):
    """
    Redoes the linear assignment problem for frames that were skipped during tracking
    """

    # remove spots in skipped frames
    spots_df = spots_df[~spots_df["frame"].isin(skip_frames)].copy()

    for frame in skip_frames:
        print(f"Reassigning skipped frame {frame}...")

        prev_frame_spots = spots_df[spots_df["frame"] == frame - 1]
        next_frame_spots = spots_df[spots_df["frame"] == frame + 1]

        if prev_frame_spots.empty or next_frame_spots.empty:
            print(
                f"  [Warning] No spots found in adjacent frames for frame {frame}. Skipping reassignment."
            )
            continue

        cost_matrix = cdist(
            prev_frame_spots[["px_z", "px_y", "px_x"]],
            next_frame_spots[["px_z", "px_y", "px_x"]],
        )

        row_ind, col_ind = linear_sum_assignment(cost_matrix)

        row_ids = prev_frame_spots.iloc[row_ind].index
        col_ids = next_frame_spots.iloc[col_ind].index

        spots_df.loc[col_ids, "parent_id"] = row_ids

    return spots_df


def run_division_mapping(dataset: Path, config: PipelineConfig):
    """
    Pipeline management
    """

    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "final_lineages.csv"
    if out_file.exists():
        print(f"[{dataset.name}] Division Mapping (Skipped: {out_file.name} exists)")
        return

    print(f"[{dataset.name}] Running Division Mapping...")

    spots_path = out_dir / "lap_tracked_spots.csv"

    if not spots_path.exists():
        print("  [Warning] LAP tracked spots not found. Skipping division mapping.")
        return

    """
    spots_df coercion
    """
    spots_df = pd.read_csv(spots_path, index_col="ix")
    spots_df = spots_df.rename(columns={"linear_track_id": "track_id"})
    print(spots_df.index)

    spots_df["parent_id"] = -1
    track_id_most_recent = {}

    for frame, spots in spots_df.groupby("frame", sort=True):
        spots["parent_id"] = spots["track_id"].map(track_id_most_recent)
        spots_df.loc[spots.index, "parent_id"] = (
            spots["parent_id"].fillna(-1).astype(int)
        )
        track_id_most_recent.update(dict(zip(spots["track_id"], spots.index)))

    from nucleitracking.models.tracklet_utils import calculate_tracks_and_tracklets

    spots_df = reassign_skipped_frames(spots_df, config.local_post.tracking.skip_frames)
    spots_df = calculate_tracks_and_tracklets(spots_df)
    spots_df = interpolate_spots(spots_df)
    print(spots_df.groupby("track_id")["tracklet_id"].nunique().value_counts())

    """
    Calculate division costs at each division
    """
    final_spots_df = map_divisions(
        spots_df, config.local_post.division_mapping.interphase_dividers
    )

    final_spots_df = calculate_tracks_and_tracklets(final_spots_df)

    print(final_spots_df.groupby("track_id")["tracklet_id"].nunique().value_counts())

    # Save the final results ready for HDF5 extraction!
    final_spots_df.to_csv(out_dir / "final_lineages.csv", index=True, index_label="ix")
    print(f"  Saved final lineages to {out_dir / 'final_lineages.csv'}")


def get_mean_traj(df, axes, n=50):
    """
    Get mean trajectory for a given DataFrame `ss` and columns `cols`.
    Interpolates the data to `n` points.
    """
    pseudo_time = np.linspace(0, 1, n)

    interpolated_axis_values = {col: [] for col in axes}

    mean_length = df.groupby("tracklet_id")[axes[0]].count().mean()

    for i, (tid, group) in enumerate(df.groupby("tracklet_id")):
        if np.abs(len(group) - mean_length) > 25:
            continue

        for col in axes:
            vals = group[col].rolling(5, 1, center=True).mean()
            vals = (vals - vals.mean()) / vals.std()

            st = np.arange(len(vals)) / len(vals)

            if np.sum(vals.isna()) > 0:
                print(f"skipping {tid} due to NaNs")
                continue

            x_interp = np.interp(pseudo_time, st, vals)
            interpolated_axis_values[col].append(x_interp)

    for col in axes:
        interpolated_axis_values[col] = np.array(interpolated_axis_values[col])
        interpolated_axis_values[col] = np.nanmean(
            interpolated_axis_values[col], axis=0
        )

    return pseudo_time, interpolated_axis_values


def map_pseudotime(warping_path, pseudotime_full, len_this_traj):
    mapping = defaultdict(list)
    for i, j in warping_path:
        mapping[i].append(j)

    pseudotime_mapped = np.full(len_this_traj, np.nan)

    for i, js in mapping.items():
        pseudotime_mapped[i] = np.mean(pseudotime_full[js])
    return pseudotime_mapped


def warp_df(df, n=100, plot_mean_traj=False):
    pseudotime_mapper = {}
    distance_mapper = {}

    axes = ["radius", "intensity_mean", "intensity_std"]

    for cycle in [11, 12, 13]:
        print(f"Processing cycle {cycle}")

        ss = df[df["cycle"] == cycle].copy()

        mean_length = ss.groupby("tracklet_id")["area"].count().mean()

        st, mean_trajectory = get_mean_traj(ss, axes, n=n)

        if plot_mean_traj:
            import matplotlib.pyplot as plt

            plt.figure(figsize=(8, 6))
            for ax in axes:
                plt.plot(st, mean_trajectory[ax], label=ax)
            plt.xlabel("Pseudotime")
            plt.ylabel("Value")
            plt.title(f"Mean Trajectory in Cycle {cycle}")
            plt.legend()
            plt.show()

        full_traj = np.stack([mean_trajectory[ax] for ax in axes], axis=1)

        pseudotime_sequences = []

        for tid, group in tqdm(ss.groupby("tracklet_id")):
            if np.abs(len(group) - mean_length) > 25:
                continue

            this_traj = []
            na_found = False

            for axis in axes:
                x = group[axis].rolling(5, 1, center=True).mean()
                x = (x - x.mean()) / x.std()
                this_traj.append(x)

                if np.sum(x.isna()) > 0:
                    print(f"skipping {tid} due to NaNs in axis {axis}")
                    na_found = True
                    break

            this_traj = np.stack(this_traj, axis=1)

            if na_found:
                continue

            seq, dis = dtw_ndim.warping_path(
                this_traj.astype(np.double),
                full_traj.astype(np.double),
                include_distance=True,
            )

            pseudotime_seq = map_pseudotime(seq, st, len(this_traj))
            pseudotime_sequences.append(pseudotime_seq)

            pseudotime_mapper.update(dict(zip(group.index, pseudotime_seq)))
            distance_mapper.update(dict.fromkeys(group.index, dis))

    df["pseudotime"] = df.index.map(pseudotime_mapper)
    df["distance"] = df.index.map(distance_mapper)

    return df


def run_dtw(dataset: Path, config: PipelineConfig):
    print(f"[{dataset.name}] Running DTW alignment...")

    spots_df = pd.read_csv(
        dataset / f"tracking_{config.param_set_name}" / "final_lineages.csv",
        index_col="ix",
    )
    spots_df = warp_df(spots_df, n=100)

    spots_df.to_csv(
        dataset
        / f"tracking_{config.param_set_name}"
        / "final_lineages_with_pseudotime.csv",
        index=True,
        index_label="ix",
    )
    print(
        f"  Saved final lineages with pseudotime to {dataset / f'tracking_{config.param_set_name}' / 'final_lineages_with_pseudotime.csv'}"
    )


def get_cylindrical_coords(
    df: pd.DataFrame, config: PipelineConfig, viewer: napari.Viewer | None = None
) -> pd.DataFrame:
    """
    conversions
    """

    um_per_px = config.metadata.um_per_px

    df["x"] = df["px_x"] * um_per_px
    df["z"] = df["px_z"] * um_per_px
    df["y"] = df["px_y"] * um_per_px
    df["area"] = df["px_area"] * um_per_px**2
    df["radius"] = (df["area"] / np.pi) ** (1 / 2)
    df["distance_from_surface"] = df["uv_z"] - 12

    pos = np.array(df[["x", "y", "z"]])
    pca = PCA(n_components=3)
    transformed_data = pca.fit_transform(pos)

    if config.local_post.data_export.show_napari:
        # run napari to allow the user to set anterior and posterior from PCA
        viewer = napari.Viewer()

    if viewer is not None:
        viewer.add_points(
            transformed_data[df["frame"] == df["frame"].max()],
            size=5,
            shading="spherical",
            name=f"[{config.param_set_name}] Final Timepoint in PCA Space",
        )

    df["pc1"] = transformed_data[:, 0]
    df["pc2"] = transformed_data[:, 1]
    df["pc3"] = transformed_data[:, 2]

    # calculate AP position, and other details
    a = config.local_post.data_export.anterior
    p = config.local_post.data_export.posterior

    df["AP_raw"] = transformed_data[:, 0]
    df["AP"] = (df["AP_raw"] - a) / (p - a)
    df["AP_um"] = df["AP"] * np.abs(a - p)
    df["AP_um_centered"] = (df["AP"] - 0.5) * np.abs(a - p)
    df["um_from_anterior"] = np.abs(df["AP_raw"] - a)
    df["um_from_posterior"] = np.abs(df["AP_raw"] - p)
    df["distance_to_pole"] = np.min(
        np.stack([df["um_from_anterior"], df["um_from_posterior"]], axis=-1), axis=-1
    )

    # calculate theta, a ccw (anterior up) traversal around the AP axis, which should be centered at dorsal.
    dorsal_pos = transformed_data[:, 1]
    dorsal_axis = pca.components_[1]

    if not config.local_post.data_export.dorsal_on_right:
        dorsal_pos = -dorsal_pos
        dorsal_axis = -dorsal_axis

    df["theta"] = np.arctan2(dorsal_pos, transformed_data[:, 2])

    vec = np.cross(dorsal_axis, pca.components_[2])
    ant_vec = pca.components_[0] * ((a > 0) - (a < 0))
    reorder = np.dot(vec, ant_vec) < 0
    if reorder:
        df["theta"] = -df["theta"]

    return df


def run_set_cylindrical_coords(
    dataset: Path, config: PipelineConfig, viewer: napari.Viewer | None = None
):
    print(f"[{dataset.name}] Setting cylindrical coordinates...")
    out_file = dataset / f"tracking_{config.param_set_name}" / "cylindrical_coords.csv"

    if out_file.exists():
        print(
            f"  [Warning] cylindrical coords processed dataset already exists at {out_file}. Skipping cylindrical coordinate calculation."
        )
        return

    lineages_path = dataset / f"tracking_{config.param_set_name}" / "final_lineages.csv"
    if not lineages_path.exists():
        print(
            f"  [Warning] Final lineages file not found at {lineages_path}. Please run division mapping first. Skipping cylindrical coordinate calculation."
        )
        return

    spots_df = pd.read_csv(
        lineages_path,
        index_col="ix",
    )
    print(spots_df.index)

    updated_df = get_cylindrical_coords(spots_df, config, viewer=viewer)

    updated_df.to_csv(out_file, index=True, index_label="ix")
    print(f"  Saved cylindrical coordinates to {out_file}")


def get_times_from_json(json_path):
    frame_times = defaultdict(list)

    json_path = Path(json_path)
    for j_file in natsorted(json_path.glob("*.json")):
        with open(j_file) as f:
            data = json.load(f)
            frame = int(j_file.stem[-3:])
            timestamps = data["processingInformation"]["acquisition"][0]["time_stamps"]

            times_seconds = [datetime.fromisoformat(t).timestamp() for t in timestamps]
            frame_times[frame].append(np.mean(times_seconds))

    mean_frame_times = {frame: np.mean(times) for frame, times in frame_times.items()}
    return mean_frame_times


def postprocess_spots_df(df: pd.DataFrame, config: PipelineConfig):
    """
    Timing calculations
    """

    frame_map = get_times_from_json(config.dataset / "json")
    print(df["frame"].unique())
    print(frame_map)
    print([k for k, v in frame_map.items() if pd.isna(v)])
    start_time = min(frame_map.values())

    df["time"] = (df["frame"].map(frame_map) - start_time) / 60

    assert df["time"].isna().sum() == 0, (
        "Some frames are missing time information. Please check the JSON files and frame mapping."
    )

    df["tracklet_start_time"] = df["tracklet_id"].map(
        df.groupby("tracklet_id")["time"].min()
    )

    cycle_starts = np.array(config.local_post.division_mapping.interphase_dividers)
    cycle_starts[0] = max(cycle_starts[0], df["frame"].min() + 1)

    t_cycle = (
        df.groupby("tracklet_id")["frame"]
        .min()
        .apply(lambda frame: np.argmax(cycle_starts > frame))
    )
    df["cycle"] = df["tracklet_id"].map(t_cycle) + 10

    print(cycle_starts)
    print(f"frames included: {df['frame'].unique()}")
    print(f"cycles detected: {df['cycle'].unique()}")

    nc11_time = df[df["cycle"] == 11].groupby("tracklet_id")["time"].min().median()
    df["time_since_nc11"] = df["time"] - nc11_time

    """
    tracklet cleaning
    -identify nuclei in trackid 0
    -identify tracklets without any relationships
    -identify tracklets with cycle length more than 6 minutes from the cycle average
    """

    best_df = df[df["track_id"] > 0].copy()
    n_tracklets = best_df["track_id"].map(
        best_df.groupby("track_id")["tracklet_id"].nunique()
    )
    best_df = best_df[n_tracklets > 1]

    t = best_df.groupby("tracklet_id")
    ts = {}
    ts["time_start"] = t["time"].min()
    ts["time_end"] = t["time"].max()
    ts["length"] = t["time"].max() - t["time"].min()
    ts["cycle"] = t["cycle"].first()

    tracklets = pd.DataFrame(ts)

    cycle_avg_length = tracklets.groupby("cycle")["length"].median()

    tracklets["cycle_avg"] = tracklets["cycle"].map(cycle_avg_length)
    tracklets["good"] = np.abs(tracklets["length"] - tracklets["cycle_avg"]) < 6
    good_tracklets = tracklets[tracklets["good"]].index

    df["problematic"] = ~df["tracklet_id"].isin(good_tracklets)

    """
    Run dtw
    """
    df = warp_df(df, n=100, plot_mean_traj=False)

    print(df.columns)

    df["id_kept"] = df.index

    keep = [
        "id_kept",
        "time_since_nc11",
        "frame",
        "z",
        "y",
        "x",
        "AP",
        "theta",
        "area",
        "radius",
        "intensity_mean",
        "intensity_std",
        "cycle",
        "px_z",
        "px_y",
        "px_x",
        "px_area",
        "uv_v",
        "uv_u",
        "uv_z",
        "uv_distance_from_edge",
        "distance_from_surface",
        "uv_area",
        "area_distortion",
        "mesh_name",
        "is_interpolated",
        "track_id",
        "tracklet_id",
        "parent_id",
        "n_children",
        "pc1",
        "pc2",
        "pc3",
        "time",
        "problematic",
        "pseudotime",
        "distance",
    ]

    return df[keep].copy()


def run_export_hdf5(dataset: Path, config: PipelineConfig):
    print(f"[{dataset.name}] Exporting to HDF5...")
    out_file = (
        dataset
        / f"tracking_{config.param_set_name}"
        / f"{config.param_set_name}_spots.h5"
    )

    if out_file.exists():
        print(
            f"  [Warning] Processed HDF5 already exists at {out_file}. Skipping export."
        )
        return

    spots_df_path = (
        dataset / f"tracking_{config.param_set_name}" / "cylindrical_coords.csv"
    )

    if not spots_df_path.exists():
        print(
            f"  [Warning] Cylindrical coords CSV not found at {spots_df_path}. Please run set_cylindrical_coords first. Skipping export."
        )
        return

    spots_df = pd.read_csv(
        spots_df_path,
        index_col="ix",
    )
    print(spots_df.index)

    final_df = postprocess_spots_df(spots_df, config)

    final_df.to_hdf(out_file, key="lineages", index=True)
    print(f"  Saved processed lineages to {out_file}")


def run_napari_vis(dataset: Path, config: PipelineConfig):
    print(f"[{dataset.name}] Running Napari Visualization...")

    final_h5 = (
        dataset / f"tracking_{config.param_set_name}" / "final_lineages_processed.h5"
    )
    if not final_h5.exists():
        print(
            f"  [Warning] Processed HDF5 not found at {final_h5}. Skipping visualization."
        )
        return

    df = pd.read_hdf(final_h5, key="lineages")

    viewer = napari.Viewer(ndisplay=3)

    import colorcet as cc

    color = [cc.glasbey[tid % 255] for tid in df["track_id"]]
    viewer.add_points(
        df[["frame", "x", "y", "z"]].values,
        name="Tracked Lineages",
        properties={
            "track_id": df["track_id"],
            "cycle": df["cycle"],
            "time": df["time_since_nc11"],
        },
        face_color=color,
        size=df["radius"] * 2,
        border_color="black",
        border_width=0.1,
    )

    color = [cc.glasbey[cycle] for cycle in df["cycle"]]
    viewer.add_points(
        df[["frame", "x", "y", "z"]].values,
        name="Cycle Colored",
        properties={
            "track_id": df["track_id"],
            "cycle": df["cycle"],
            "time": df["time_since_nc11"],
        },
        face_color=color,
        size=df["radius"] * 2,
        border_color="black",
        border_width=0.1,
    )
    viewer.theme = "dark"
    napari.run()
