from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment
from scipy.spatial.distance import cdist

from nucleitracking.models.division_tracking import map_divisions
from nucleitracking.models.lap_tracking import run_lap_tracking
from nucleitracking.pipeline.config import PipelineConfig


def merge_centroids(current_centroids, centroids_to_add, max_distance=25):
    """
    Merges centroids from `centroids_to_add` into `current_centroids` if they are within `max_distance`.
    """
    axes = ["px_z", "px_y", "px_x"]

    merged_centroids = current_centroids.copy()
    add_to_drop = set()
    merged_to_drop = set()

    for timepoint in set(current_centroids["timepoint"]).intersection(
        set(centroids_to_add["timepoint"])
    ):
        current = current_centroids[current_centroids["timepoint"] == timepoint]
        to_add = centroids_to_add[centroids_to_add["timepoint"] == timepoint]

        x_current = current[axes].values
        x_add = to_add[axes].values

        distances = cdist(x_current, x_add)
        close_pairs = np.argwhere(distances < max_distance)

        for i, j in close_pairs:
            # keep the centroids farthest from the edge
            if (
                to_add.iloc[j]["uv_distance_from_edge"]
                < current.iloc[i]["uv_distance_from_edge"]
            ):
                add_to_drop.add(to_add.index[j])
            else:
                merged_to_drop.add(current.index[i])

    out = pd.concat(
        [merged_centroids.drop(merged_to_drop), centroids_to_add.drop(add_to_drop)],
        ignore_index=True,
    )

    return out


def run_merge_centroids(dataset: Path, config: PipelineConfig):
    """
    Reads the 2D centroids generated by the batched script on the cluster,
    and merges them into a single 3D global cloud.
    """
    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "new_centroids.csv"
    if out_file.exists():
        print(
            f"[{dataset.name}] Merging 3D Centroids (Skipped: {out_file.name} exists)"
        )
        return

    print(f"[{dataset.name}] Merging 3D Centroids...")
    csv_path = out_dir / "centroids_2d_from_stack.csv"

    if not csv_path.exists():
        print(f"  [Error] {csv_path} not found.")
        print("  ACTION REQUIRED:")
        print(
            "  Run the batched 2D clustering script and place the output here before resuming local_post."
        )
        return

    centroids = pd.read_csv(csv_path)

    centroids["px_area"] = centroids["px_area"].abs()
    centroids = centroids[centroids["px_area"] < 300]

    new_centroids = None
    meshes = centroids["mesh_name"].unique()

    for mesh_name in meshes:
        print(f"  Merging {mesh_name} into global cloud")
        to_add = centroids[centroids["mesh_name"] == mesh_name]

        if new_centroids is None:
            new_centroids = to_add
            continue

        new_centroids = merge_centroids(
            new_centroids,
            to_add,
            max_distance=config.local_post.reconstruct_3d.max_distance,
        )

    new_centroids = new_centroids.dropna()
    new_centroids = new_centroids.reset_index(drop=True)
    new_centroids["id_prev"] = new_centroids.index.astype(np.uint32)

    # Convert column names to match downstream tracking expectations
    new_centroids = new_centroids.rename(
        columns={
            "timepoint": "frame",
        }
    )

    out_file = out_dir / "new_centroids.csv"
    new_centroids.to_csv(out_file, index=False)
    print(f"  Saved reconstructed 3D centroids to {out_file}")


# def run_napari_visualization(dataset: Path, config: PipelineConfig):
#     """
#     Opens the final lineages CSV in a 3D Napari viewer, mirroring coordinates
#     and applying a discrete color palette to track IDs.
#     """
#     out_dir = dataset / f"tracking_{config.param_set_name}"
#     final_csv = out_dir / "final_lineages.csv"
#
#     if not final_csv.exists():
#         print(f"  [Warning] {final_csv.name} not found. Skipping visualization.")
#         return
#
#     print(f"[{dataset.name}] Opening Napari Visualization...")
#     import colorcet as cc
#     import napari
#
#     df = pd.read_csv(final_csv)
#
#     # Reflect coordinates to "unwrap" the cylinder if possible
#     if "px_z" in df.columns and "px_x" in df.columns.values:
#         df["reflection_z"] = 2.1 * df["px_z"].max() - df["px_z"]
#         df["reflection_x"] = df["px_x"].max() - df["px_x"]
#         df["is_reflected"] = df["px_x"] > df["px_x"].max() / 2
#
#         df["display_x"] = df["reflection_x"] * df["is_reflected"] + df["px_x"] * (
#             ~df["is_reflected"]
#         )
#         df["display_z"] = df["reflection_z"] * df["is_reflected"] + df["px_z"] * (
#             ~df["is_reflected"]
#         )
#     else:
#         df["display_x"] = df.get("px_x", np.zeros(len(df)))
#         df["display_z"] = df.get("px_z", np.zeros(len(df)))
#
#     column = "track_id"
#     if column not in df.columns:
#         print(
#             f"  [Warning] '{column}' not in {final_csv.name}. Displaying points in white."
#         )
#         color = "white"
#         properties = None
#     else:
#         track_ids = np.nan_to_num(df[column].unique())
#         palette = cc.glasbey  # Discrete categorical palette
#         color_map = {
#             track: palette[i % len(palette)] for i, track in enumerate(track_ids)
#         }
#         color = [color_map[track] for track in df[column].fillna(0)]
#         properties = {"spot id": df.index, column: df[column]}
#
#     # Prepare coordinate matrix (T, Z, Y, X in napari by default, but we'll use T, X, Y, Z for 3D)
#     # Napari expects (T, Z, Y, X) for points to be displayed in the correct orientation usually.
#     coords = df[["FRAME", "display_x", "px_y", "display_z"]].values
#
#     viewer = napari.Viewer(ndisplay=3)
#     viewer.add_points(
#         coords,
#         name="Tracked Lineages",
#         properties=properties,
#         face_color=color,
#         size=13,
#     )
#     viewer.theme = "dark"
#     napari.run()


def interpolate_spots(spots_df: pd.DataFrame):
    """
    Interpolates the positions of spots in the spots_df to fill in gaps between frames.
    This does not use the graph structure
    """

    spots_df["frame_gap"] = spots_df["frame"] - spots_df["parent_id"].map(
        spots_df["frame"]
    )
    spots_df["is_interpolated"] = False

    children = spots_df[spots_df["frame_gap"] > 1]

    new_rows = []
    new_indices = []
    next_highest_id = spots_df.index.max() + 1

    for idx, child in children.iterrows():
        parent = spots_df.loc[child["parent_id"]]
        gap = child["frame_gap"]

        next_parent_id = child["parent_id"]

        for i in range(1, int(gap)):
            interp_spot = {
                "frame": parent["frame"] + i,
                "px_z": parent["px_z"] + (child["px_z"] - parent["px_z"]) * i / gap,
                "px_y": parent["px_y"] + (child["px_y"] - parent["px_y"]) * i / gap,
                "px_x": parent["px_x"] + (child["px_x"] - parent["px_x"]) * i / gap,
                "track_id": parent["track_id"],
                "parent_id": next_parent_id,
                "is_interpolated": True,
            }

            row = spots_df.loc[idx].copy()
            row.update(interp_spot)
            new_rows.append(row)
            new_indices.append(next_highest_id)
            next_parent_id = next_highest_id
            next_highest_id += 1

        spots_df.loc[idx, "parent_id"] = next_parent_id

    if new_rows:
        new_spots_df = pd.DataFrame(new_rows, index=new_indices)
        spots_df = pd.concat([spots_df, new_spots_df])

    return spots_df.sort_values("frame")


def reassign_skipped_frames(spots_df: pd.DataFrame, skip_frames: list):
    """
    Redoes the linear assignment problem for frames that were skipped during tracking
    """

    # remove spots in skipped frames
    spots_df = spots_df[~spots_df["frame"].isin(skip_frames)].copy()

    for frame in skip_frames:
        print(f"Reassigning skipped frame {frame}...")

        prev_frame_spots = spots_df[spots_df["frame"] == frame - 1]
        next_frame_spots = spots_df[spots_df["frame"] == frame + 1]

        if prev_frame_spots.empty or next_frame_spots.empty:
            print(
                f"  [Warning] No spots found in adjacent frames for frame {frame}. Skipping reassignment."
            )
            continue

        cost_matrix = cdist(
            prev_frame_spots[["px_z", "px_y", "px_x"]],
            next_frame_spots[["px_z", "px_y", "px_x"]],
        )

        row_ind, col_ind = linear_sum_assignment(cost_matrix)

        row_ids = prev_frame_spots.iloc[row_ind].index
        col_ids = next_frame_spots.iloc[col_ind].index

        spots_df.loc[col_ids, "parent_id"] = row_ids

    return spots_df


def run_division_mapping(dataset: Path, config: PipelineConfig):
    """
    Pipeline management
    """

    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "final_lineages.csv"
    if out_file.exists():
        print(f"[{dataset.name}] Division Mapping (Skipped: {out_file.name} exists)")
        return

    print(f"[{dataset.name}] Running Division Mapping...")

    spots_path = out_dir / "lap_tracked_spots.csv"

    if not spots_path.exists():
        print("  [Warning] LAP tracked spots not found. Skipping division mapping.")
        return

    """
    spots_df coercion
    """
    spots_df = pd.read_csv(spots_path)
    spots_df = spots_df.rename(columns={"linear_track_id": "track_id"})

    spots_df["parent_id"] = -1
    track_id_most_recent = {}

    for frame, spots in spots_df.groupby("frame", sort=True):
        spots["parent_id"] = spots["track_id"].map(track_id_most_recent)
        spots_df.loc[spots.index, "parent_id"] = (
            spots["parent_id"].fillna(-1).astype(int)
        )
        track_id_most_recent.update(dict(zip(spots["track_id"], spots.index)))

    from nucleitracking.models.tracklet_utils import calculate_tracks_and_tracklets

    spots_df = reassign_skipped_frames(spots_df, config.local_post.tracking.skip_frames)
    spots_df = calculate_tracks_and_tracklets(spots_df)
    spots_df = interpolate_spots(spots_df)
    print(spots_df.groupby("track_id")["tracklet_id"].nunique().value_counts())

    """
    Calculate division costs at each division
    """
    spots_df = map_divisions(
        spots_df, config.local_post.division_mapping.interphase_dividers
    )

    spots_df = calculate_tracks_and_tracklets(spots_df)

    print(spots_df.groupby("track_id")["tracklet_id"].nunique().value_counts())

    import colorcet as cc
    import napari

    positions = spots_df[["frame", "px_z", "px_y", "px_x"]].values
    colors = [cc.glasbey[i % len(cc.glasbey)] for i in spots_df["track_id"]]

    viewer = napari.Viewer(ndisplay=3)
    viewer.add_points(
        positions,
        face_color=colors,
        size=10,
        properties={
            "track_id": spots_df["track_id"],
            "is_interpolated": spots_df["is_interpolated"],
            "parent_id": spots_df["parent_id"],
        },
    )
    napari.run()

    # graph = nx.DiGraph()
    #
    # track_id_most_recent = {}
    #
    # for frame, spots in spots_df.groupby("frame"):
    #     parents = spots["linear_track_id"].map(track_id_most_recent)
    #
    #     for parent, child in zip(parents, spots[["graph_key"]]):
    #         if pd.isna(parent):
    #             continue
    #         graph.add_edge(parent, child, time=1)
    #
    #     track_id_most_recent.update(
    #         dict(spots[["linear_track_id", "graph_key"]].values)
    #     )
    #
    # print("  Interpolating points...")
    # interpolated_spots_df, interpolated_graph = interpolate_points(spots_df, graph)

    # print("  Merging close tracklets...")
    # merged_spots_df, merged_graph = merge_close_tracklets(
    #     interpolated_spots_df, interpolated_graph, max_dis=12
    # )

    # print("  Mapping divisions...")
    # mapped_graph, _test_spots_df = map_divisions(
    #     interpolated_spots_df,
    #     interpolated_graph,
    #     config.local_post.division_mapping.interphase_dividers,
    #     new_track_cost=config.local_post.division_mapping.new_track_cost,
    # )
    #
    # print("  Processing final lineage graph...")
    # final_spots_df = process_graph(interpolated_spots_df, mapped_graph)
    #
    # # Save the final results ready for HDF5 extraction!
    # final_spots_df.to_csv(out_dir / "final_lineages.csv", index=False)
    # print(f"  Saved final lineages to {out_dir / 'final_lineages.csv'}")


def run_tracking(dataset: Path, config: PipelineConfig):
    out_dir = dataset / f"tracking_{config.param_set_name}"
    out_file = out_dir / "lap_tracked_spots.csv"
    if out_file.exists():
        print(f"[{dataset.name}] LAP Tracking (Skipped: {out_file.name} exists)")
        return

    print(f"[{dataset.name}] Running LAP Tracking...")

    # Load 3D centroids generated from the local post-processing Reconstruction step
    # For now, we assume a standard name
    centroids_path = dataset / f"tracking_{config.param_set_name}" / "new_centroids.csv"
    if not centroids_path.exists():
        print(
            f"  [Warning] Centroids file not found at {centroids_path}. Skipping tracking."
        )
        return

    centroids = pd.read_csv(centroids_path)

    # Filter frames based on user configuration
    if config.local_post.tracking.start_frame > 0:
        print(
            f"  Filtering out frames before {config.local_post.tracking.start_frame}..."
        )
        centroids = centroids[
            centroids["frame"] >= config.local_post.tracking.start_frame
        ]

    if config.local_post.tracking.skip_frames:
        print(f"  Skipping frames: {config.local_post.tracking.skip_frames}...")
        centroids = centroids[
            ~centroids["frame"].isin(config.local_post.tracking.skip_frames)
        ]

    # Run the new Python LAP tracker instead of TrackMate
    spots_df, _graph = run_lap_tracking(
        centroids,
        max_distance=config.local_post.tracking.search_radius,
        max_gap_frames=config.local_post.tracking.max_gap_frames,
    )

    # Save preliminary tracking results
    out_dir = dataset / f"tracking_{config.param_set_name}"
    spots_df.to_csv(out_dir / "lap_tracked_spots.csv", index=False)
    print(f"  Saved LAP tracked spots to {out_dir / 'lap_tracked_spots.csv'}")
